version: "3.8"
services:

  nginx:
    image: nginx:latest
    ports:
      - "15000:15000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
      - server3

  server1:
    build: .
    ports:
      - "15001:15000"
    environment:
      - POSTGRES_URL=postgres://postgres:12345678@db:5432/postgres?sslmode=disable
      - SECRET_KEY_JWT=pink-chocolate
      - RABBITMQ_URL=amqp://guest:guest@localhost:5672/
    depends_on:
      - db
      - rabbit
    restart: unless-stopped

  server2:
    build: .
    ports:
      - "15002:15000"
    environment:
      - POSTGRES_URL=postgres://postgres:12345678@db:5432/postgres?sslmode=disable
      - SECRET_KEY_JWT=pink-chocolate
      - RABBITMQ_URL=amqp://guest:guest@localhost:5672/
    depends_on:
      - db
      - rabbit
    restart: unless-stopped

  server3:
    build: .
    ports:
      - "15003:15000"
    environment:
      - POSTGRES_URL=postgres://postgres:12345678@db:5432/postgres?sslmode=disable
      - SECRET_KEY_JWT=pink-chocolate
      - RABBITMQ_URL=amqp://guest:guest@localhost:5672/
    depends_on:
      - db
      - rabbit
    restart: unless-stopped


  rabbit:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbit_data:/var/lib/rabbitmq

  db:
    image:  docker.arvancloud.ir/postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  rabbit_data:
  postgres_data: